dist: xenial
language: generic
script:
  - docker build -t diuid .
  - time docker run --cap-add=SYS_PTRACE --rm diuid docker run hello-world
  - |
    set -x && \
    docker run --cap-add=SYS_PTRACE -d --name diuid-nginx -p 80:80 diuid docker run -p 80:80 nginx:alpine && \
    for i in {1..5}; do curl http://localhost && break || sleep 10; done && \
    docker rm -f diuid-nginx
